### PR TITLE
Add SQLAlchemy-Utils

### PR DESCRIPTION
**Pull request by osya**

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
I don't think it is a good idea to force sqlalchemy-utils on all users, since it is only a subset of the sqlalchemy user base that wants it. I would accept the contribution if it used a separate template and didn't include the sqlalchemy-utils dependency, though.

**Comment by osya** [comment]
Ok, @miguelgrinberg . Could you please explain a bit more details how to add new template appropriately in SQLAlchemy-Utils? May be some examples? I am so good understand its architecture.

**Comment by miguelgrinberg** [comment]
Take a look at how the multidb feature is implemented. I think a similar model can be used to for sqlalchemy-utils, where during the creation of the migration repository the user can say something like `./manage.py db create --sqlalchemy-utils` to have the repository configured for that.

**Comment by miguelgrinberg** [comment]
This issue will be automatically closed due to being inactive for more than six months. Please reopen if you need more assistance.

**Pull request closed without merging**
