### PR TITLE
Add the instruction for running db commands when using application fa…

### PR DESCRIPTION
**Pull request by ValkoVolodya**
Add the instruction for running db commands when using application factory function.

I really struggled to find solution for this, so added this paragraph to clarify how to run commands correctly with application factory function.

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
I don't feel it is necessary to duplicate the Flask documentation here. The paragraph that you added is not specific to Flask-Migrate, you are required to do this if you want to use the `flask run` or actually and `flask` command. This documentation also does not mention how to configure your Flask application when not using an application factory function, so it is also strange to explain how to configure the app factory but not a standard application instance.

**Comment by ValkoVolodya** [comment]
@miguelgrinberg Flask itself perfectly working with onlу specifying module to run, without application function - ``FLASK_APP=<your_app_name>``(this is mentioned in Flask docs - https://flask.palletsprojects.com/en/2.3.x/patterns/appfactories/#using-applications), but Flask-Migrate works only with ``FLASK_APP=<your_app_name>:<<app factory func>>`` which is not obvious(.

**Comment by ValkoVolodya** [comment]
Created a little repo when this problem reproduces - https://github.com/ValkoVolodya/test_flask_migrate/tree/master
Maybe, this repo structure is not right? But seems okay to me.

**Comment by miguelgrinberg** [comment]
This is a bug in your application.

In [this line](https://github.com/ValkoVolodya/test_flask_migrate/blob/master/test_flask_migrate/__init__.py#L5) you create a Flask application instance bypassing your app factory function. Flask always prefers instances to factories, so it finds this instance first, and goes with it. Obviously this instance does not have any extensions registered to it, and in particular because Flask-Migrate isn't registered its commands are not accessible. This would happen with any other extensions that register custom commands as well, it is not specific to Flask-Migrate.

**Comment by ValkoVolodya** [comment]
Now I see, so it`s my fault, thanks for explaining!
Have a good day!

**Pull request closed without merging**
