### PR TITLE
Refactor structure, make it more extensible.

### PR DESCRIPTION
**Pull request by fantix**
~~This is a breaking change, though it can be backward compatible with some global tricks.~~

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
Not super excited about introducing breaking changes. What's the problem you are trying to solve by refactoring the whole extension?

**Comment by fantix** [comment]
Mostly I wanted to override a few commands as well as the config, while not wanting to *replace* a certain method in the extension, for example `_get_config`. Let me push the compatibility fix, see if that is sufficient to make it smooth.

**Comment by fantix** [comment]
@miguelgrinberg Fixed :) Please check, thanks!

**Comment by fantix** [comment]
One of my previous hack looks like this:
```python
def _patch_migrate():
    _old_get_config = flask_migrate._get_config

    def _get_config(directory, x_arg=None, opts=None):
        if directory is None:
            directory = current_app.extensions['migrate'].directory
        ret = _old_get_config(directory, x_arg, opts)
        ret.set_main_option('version_locations', ' '.join((
            os.path.join(os.path.dirname(__file__), 'versions'),
            os.path.join(directory, 'versions'),
        )))
        return ret

    flask_migrate._get_config = _get_config


_patch_migrate()
del _patch_migrate
```

**Comment by miguelgrinberg** [comment]
This change still breaks a currently supported use case, which is to invoke the commands programmatically, something that is very useful in deployment scripts. Example:

    # migrate database to latest revision
    from flask_migrate import upgrade
    upgrade()

How about a completely different approach. I could provide a configuration hook, through a decorated function. Maybe something like this:

    @migrate.configure
    def alembic_configure(config)
        # ... change the config object as you need ...
        return config

Would that work?

**Comment by fantix** [comment]
Sounds like a plan :) Thanks for that! Please carry on (or shall I create another PR?) and I'll take a look. Meanwhile I'll update this PR trying to support the broken case. Thanks!

**Comment by miguelgrinberg** [comment]
@fantix Before I do a release, could you check that the configure callbacks I implemented in the last commit do what you need?

Thanks!

**Comment by fantix** [comment]
@miguelgrinberg Sure thing! Thanks a lot for the fix! Let me try.

**Comment by fantix** [comment]
Your commit 835d3e4b33bfbd7dae2166b88c49aee8f5fbeac0 works well for me!

**Pull request closed without merging**
